### ISSUE TITLE
refactor: ai, diary 코드 리팩토링

### ISSUE THREAD

**Issue by stableh** [canvi-likelion/canvi-server#25]
## 📋 이슈 유형
- 개선 사항 (Improvement)

## 📝 관련 이슈, PR
- #6
- #12 

## ✅ Todo
- [x] 생성자 @RequiredArgsConstructor로 변경
- [x] 단수, 복수형 점검
- [x] api url 동사에서 명사로
- [x] @Data 제거 
- [x] @NotNull로 변경
- [ ] #34
- [x] 이미지 저장 방식 Files.readAllBytes()에서 Resource로 변경하기
- [x] 변수명, 메서드명 점검
- [x] #35
- [x] id 외래키들 변수명 확인
- [x] dto record로 변경
- [x] controller 레이어에서 repository 사용하지 않도록 변경
